import { ClerkProvider, UserButton } from '@clerk/nextjs';
import './globals.css'


export const metadata = {
  title: "My App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body>
        <ClerkProvider>
          <UserButton />
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
